# Generated by Django 3.2.10 on 2022-09-19 10:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20220914_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='copiedemail1',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='copiedemails2',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='copiedemails3',
        ),
        migrations.RemoveField(
            model_name='laserrep',
            name='position',
        ),
        migrations.AddField(
            model_name='dataset',
            name='file_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='file_title10',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='file_title2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='file_title3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='file_title4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='file_title5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='file_title6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='file_title7',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='file_title8',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='file_title9',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='pdf10',
            field=models.FileField(blank=True, null=True, upload_to='raw/'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='pdf2',
            field=models.FileField(blank=True, null=True, upload_to='raw/'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='pdf3',
            field=models.FileField(blank=True, null=True, upload_to='raw/'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='pdf4',
            field=models.FileField(blank=True, null=True, upload_to='raw/'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='pdf5',
            field=models.FileField(blank=True, null=True, upload_to='raw/'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='pdf6',
            field=models.FileField(blank=True, null=True, upload_to='raw/'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='pdf7',
            field=models.FileField(blank=True, null=True, upload_to='raw/'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='pdf8',
            field=models.FileField(blank=True, null=True, upload_to='raw/'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='pdf9',
            field=models.FileField(blank=True, null=True, upload_to='raw/'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='progressreport',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='laserrep',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laserrep',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='adminlaser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 10, 8, 46, 572558, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='adminlaser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 10, 8, 46, 572558, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 10, 8, 46, 572558, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 10, 8, 46, 572558, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='clientrep',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='clientrep_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='copiedemails',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 10, 8, 46, 575554, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='jobkey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='pvt_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackclient',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 10, 8, 46, 578552, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='laserrep',
            name='laserrep_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notificationclient',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 10, 8, 46, 578552, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notificationclient',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 10, 8, 46, 578552, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 10, 8, 46, 577553, tzinfo=utc)),
        ),
    ]
