# Generated by Django 3.2.10 on 2022-08-17 10:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20220817_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlaser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 10, 49, 44, 853507, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='adminlaser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 10, 49, 44, 853507, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 10, 49, 44, 853507, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 10, 49, 44, 853507, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 10, 49, 44, 853507, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='jobstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.jobstatus'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='jobstatus1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobstatus_1', to='client.jobstatus'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='jobstatus2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobstatus_2', to='client.jobstatus'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='jobstatus3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobstatus_3', to='client.jobstatus'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='jobstatus4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobstatus_4', to='client.jobstatus'),
        ),
        migrations.AlterField(
            model_name='feedbackclient',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 10, 49, 44, 853507, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notificationclient',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 10, 49, 44, 853507, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notificationclient',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 10, 49, 44, 853507, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 10, 49, 44, 853507, tzinfo=utc)),
        ),
    ]
