# Generated by Django 3.2.10 on 2022-12-07 10:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_auto_20221202_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='clientrep_email1',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='clientrep_email10',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='clientrep_email11',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='clientrep_email2',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='clientrep_email3',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='clientrep_email4',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='clientrep_email5',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='clientrep_email6',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='clientrep_email7',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='clientrep_email8',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='clientrep_email9',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='copiedemails',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='copiedemails1',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='copiedemails2',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='copiedemails3',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='copiedemails4',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='copiedemails5',
        ),
        migrations.AlterField(
            model_name='adminlaser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 10, 13, 19, 967359, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='adminlaser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 10, 13, 19, 967359, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 10, 13, 19, 967359, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 10, 13, 19, 967359, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 10, 13, 19, 967359, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='feedbackclient',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 10, 13, 19, 967359, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notificationclient',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 10, 13, 19, 967359, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notificationclient',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 10, 13, 19, 967359, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 10, 13, 19, 967359, tzinfo=utc)),
        ),
    ]
